//Home
get http://localhost:3000/
###

//Cuisines
// 1: GET /api/cuisines
get http://localhost:3000/api/cuisines   

###
// 2: GET /api/cuisines/:id
get http://localhost:3000/api/cuisines/64ad37058e906588bac718b7 

###
// 3 : POST /api/cuisines
post http://localhost:3000/api/cuisines
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "German"
}

###
// 4: PUT /api/cuisines/:id
put http://localhost:3000/api/cuisines/64b699fe485f6af6833eb048
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testName"
}

###
// 5: DELETE /api/cuisines/:id
delete http://localhost:3000/api/cuisines/64b699fe485f6af6833eb048
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmZmY3ZWU0OGRiOWE2MGUwZjU0MmUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODk2ODY3Mjl9.B7GV35qUw05IxUapjqFh2EWRLEtzj_sT6K_9GazUtBU

###
//Customers
// 1: GET /api/customers
get http://localhost:3000/api/customers   

###
// 2: GET /api/customers/:id
get http://localhost:3000/api/customers/64a82114a957f010a83b8c48

###
// 3 : POST /api/customers
post http://localhost:3000/api/customers
Content-Type: application/json

{
    "name": "testUser",
    "phone": "+32111111111",
    "email": "test@gmail.com"
}

###
// 4: PUT /api/customers/:id
put http://localhost:3000/api/customers/64abe7af8b9e51fa86e9ef9a
Content-Type: application/json

{
    "name": "testUser2",
    "phone": "+32222222222",
    "email": "test2@gmail.com"
}

###
// 5: DELETE /api/customers/:id
delete http://localhost:3000/api/customers/64a82114a957f010a83b8c48
Content-Type: application/json

###
//Dishes
// 1: GET /api/dishes
get http://localhost:3000/api/dishes

###
// 2: GET /api/dishes/:id
get http://localhost:3000/api/dishes/64abeae4842f9fe2a9739f1b

###
// 3 : POST /api/dishes
post http://localhost:3000/api/dishes
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testDish",
    "ingredients": [
      "ingredient1",
      "ingredient2",
      "ingredient3"
    ],
    "cuisineId": "64ad37058e906588bac718b7",
    "calories": 200,
    "price": 20
}

###
// 4: PUT /api/dishes/:id
put http://localhost:3000/api/dishes/64b7c54b2d5d4bf8b15655ee
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testDish0",
    "ingredients": [
      "ingredient0"
    ],
    "cuisineId": "64ad37058e906588bac718b7",
    "calories": 100,
    "price": 10
}

###
// 5: DELETE /api/dishes/:id
delete http://localhost:3000/api/dishes/64ad385e8e906588bac718cd
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmZmY3ZWU0OGRiOWE2MGUwZjU0MmUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODk2ODY3Mjl9.B7GV35qUw05IxUapjqFh2EWRLEtzj_sT6K_9GazUtBU

###
//Orders
// 1: GET /api/orders
get http://localhost:3000/api/orders

###
// 2: GET /api/orders/:id
get http://localhost:3000/api/orders/64abec9e842f9fe2a9739f28

###
// 3 : POST /api/orders
post http://localhost:3000/api/orders
Content-Type: application/json

{
    "customer": "testCustomer",
    "dish": "testDish"
}

###
// 4: PUT /api/orders/:id
put http://localhost:3000/api/orders/64abec9e842f9fe2a9739f28
Content-Type: application/json

{
    "customer": "testCustomer0",
    "dish": "testDish0"
}

###
// 5: DELETE /api/orders/:id
delete http://localhost:3000/api/orders/64abec9e842f9fe2a9739f28
Content-Type: application/json

###
//Auth
// 1: POST /api/auth
post http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "sylwia.admin@vives.be",
    "password": "12345"
}

###

//Users
// 1: POST /api/users
post http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "testSylwia",
    "email": "sylwiaTest4@vives.be",
    "password": "12345",
    "isAdmin": false
}

###

// 2: GET /api/users/me
get http://localhost:3000/api/users/me/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

###