//Home
get http://localhost:3000/
###

//Cuisines
// 1: GET /api/cuisines
get http://localhost:3000/api/cuisines   

###
// 2: GET /api/cuisines/:id
get http://localhost:3000/api/cuisines/64ad37058e906588bac718b7 

###
// 3 : POST /api/cuisines
post http://localhost:3000/api/cuisines
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "German"
}

###
// 4: PUT /api/cuisines/:id
put http://localhost:3000/api/cuisines/64b91fd999aef4b7b5121f8c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testName"
}

###
// 5: DELETE /api/cuisines/:id
delete http://localhost:3000/api/cuisines/64b91fd999aef4b7b5121f8c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmZmY3ZWU0OGRiOWE2MGUwZjU0MmUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODk2ODY3Mjl9.B7GV35qUw05IxUapjqFh2EWRLEtzj_sT6K_9GazUtBU

###
//Customers
// 1: GET /api/customers
get http://localhost:3000/api/customers   

###
// 2: GET /api/customers/:id
get http://localhost:3000/api/customers/64ad38bf8e906588bac718d0

###
// 3 : POST /api/customers
post http://localhost:3000/api/customers
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testCustomer",
    "phone": "+32111111111"
}

###
// 4: PUT /api/customers/:id
put http://localhost:3000/api/customers/64b925bf7af5a57c4f366766
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testCustomer2",
    "phone": "+32222222222"
}

###
// 5: DELETE /api/customers/:id
delete http://localhost:3000/api/customers/64b925bf7af5a57c4f366766
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmZmY3ZWU0OGRiOWE2MGUwZjU0MmUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODk2ODY3Mjl9.B7GV35qUw05IxUapjqFh2EWRLEtzj_sT6K_9GazUtBU

###
//Dishes
// 1: GET /api/dishes
get http://localhost:3000/api/dishes

###
// 2: GET /api/dishes/:id
get http://localhost:3000/api/dishes/64b7b0025b095187e23b7641

###
// 3 : POST /api/dishes
post http://localhost:3000/api/dishes
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testDish",
    "ingredients": [
      "ingredient1",
      "ingredient2",
      "ingredient3"
    ],
    "cuisineId": "64ad37058e906588bac718b7",
    "calories": 200,
    "price": 20
}

###
// 4: PUT /api/dishes/:id
put http://localhost:3000/api/dishes/64b9203e521c025e8e7a733c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "name": "testDish0",
    "ingredients": [
      "ingredient0"
    ],
    "cuisineId": "64ad37058e906588bac718b7",
    "calories": 100,
    "price": 10
}

###
// 5: DELETE /api/dishes/:id
delete http://localhost:3000/api/dishes/64b9203e521c025e8e7a733c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmZmY3ZWU0OGRiOWE2MGUwZjU0MmUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODk2ODY3Mjl9.B7GV35qUw05IxUapjqFh2EWRLEtzj_sT6K_9GazUtBU

###
//Orders
// 1: GET /api/orders
get http://localhost:3000/api/orders

###
// 2: GET /api/orders/:id
get http://localhost:3000/api/orders/64ad39588e906588bac718d8

###
// 3 : POST /api/orders
post http://localhost:3000/api/orders
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "customerId": "64b926e2c41b4684a0b21b54",
    "dishId": "64ad37998e906588bac718c1"
}

###
// 4: PUT /api/orders/:id
put http://localhost:3000/api/orders/64b92ad4bbc2d154c5e8596b
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmY2ZlZjdkNzNhYjJmYmE0ZjJhMmQiLCJpYXQiOjE2ODkyNTI3MjR9.OuXES1yHgpIqxeXcKJ56hQNqBx8-ts-HaHgleyWdCTs

{
    "customerId": "64b926e2c41b4684a0b21b54",
    "dishId": "64ad37df8e906588bac718c5"
}

###
// 5: DELETE /api/orders/:id
delete http://localhost:3000/api/orders/64abec9e842f9fe2a9739f28
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFmZmY3ZWU0OGRiOWE2MGUwZjU0MmUiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODk2ODY3Mjl9.B7GV35qUw05IxUapjqFh2EWRLEtzj_sT6K_9GazUtBU

###
//Auth
// 1: POST /api/auth
post http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "sylwia.admin@vives.be",
    "password": "12345"
}

###

//Users
// 1: POST /api/users
post http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "testSylwia",
    "email": "sylwiaTest7@vives.be",
    "password": "12345",
    "isAdmin": false
}

###

// 2: GET /api/users/me
get http://localhost:3000/api/users/me/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGI5M2ExNWQ3M2NjZjVhMzQ4MDJmYzIiLCJpYXQiOjE2ODk4NjEwMjN9.QAXt1v6t5H0su-3MxBYx-5KZAWOWTqQrUA8e9NUh-v8

###


//Auth
// 1: POST /api/auth
post http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "sylwiaTest8@vives.be",
    "password": "12345"
}

###