# CUISINE CALLS #
# Variables
@base_URL=http://localhost:3000/api/cuisines 
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxMTc4ZTRiNzVlNGIyZDFhOGUxODQiLCJpYXQiOjE2OTE0MjQ2NTR9.APLWx9IQUxM4GBGJCzH0tLn5UJHIcvutqx-E6ugcbmM

@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxMzE2NzNiOGRjMGQwNGViNjBlODEiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2OTE0MzEyNzF9.5bCoeEEGFnrusHRjB4YfOBh-ojD95GEaqk3W0Gfoogc

//GET 
get {{base_URL}}  

###
//GET /:id
@objId1=64ad37058e906588bac718b7
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
//POST
post {{base_URL}}
Content-Type: application/json
x-auth-token: {{token}}

//"name": "Greek" //min 3 string
{
    "name": "German"
}

###
//PUT /:id
@objId2=64d117eb4b75e4b2d1a8e186
put {{base_URL}}/{{objId2}}
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": "testName2"
}

###
//DELETE /:id
@objId3=64d11a9f4b75e4b2d1a8e18f
delete {{base_URL}}/{{objId3}}
Content-Type: application/json
x-auth-token: {{token2}}

###