# USER CALL #
# Variables
@base_URL=http://localhost:3000/api/users 

//POST
post {{base_URL}}
Content-Type: application/json

//"name": "testSylwia", //5 to 50 string
//"email": "sylwiaTest718@vives.be", //5 to 255 string
//"password": "12345", //5 to 1024 string
//"isAdmin": false //boolean
{
    "name": "testSylwia",
    "email": "sylwiaTestAdmin11@vives.be",
    "password": "12345",
    "isAdmin": true
}

###

//GET /me
get {{base_URL}}/me/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQxMmQ1OWRjOWM2ZjhmMTkxOTMyMjQiLCJpYXQiOjE2OTE0MzAyMzN9.DkpNDXLg-zTrqjg8xT7EEAL3-CsfYhf-TUAmB-s9wK4

###